---
- name: Install development related packages
  become: yes
  apt:
    name:
      - build-essential
      - clang
      - git
      - autoconf
      - bison
      - gcc
      - make
      - zlib1g-dev
      - libffi-dev
      - libreadline-dev
      - libgdm-dev
      - libssl-dev
      - universal-ctags
      - global
      - r-base
      - jq
      
- name: Stow Git config
  stow:
    name: git
    source: "{{ dotfile_path }}"
    overwrite_conflicts: yes

- name: Create source code directory
  file:
    path: "{{ ansible_env .HOME }}/src"
    state: directory

- name: Clone Ruby
  git:
    repo: "git@github.com:Shopify/ruby.git"
    dest: "{{ ansible_env .HOME }}/src/ruby"
    update: no

- name: Install rbenv
  git:
    repo: "https://github.com/rbenv/rbenv.git"
    dest: "{{ ansible_env .HOME }}/.rbenv"
    update: no

- name: Make rbenv plugins dir
  file:
    path: "{{ ansible_env .HOME }}/.rbenv/plugins"
    state: directory

- name: Install ruby-build
  git:
    repo: "https://github.com/rbenv/ruby-build.git"
    dest: "{{ ansible_env .HOME }}/.rbenv/plugins/ruby-build"
    update: no

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Download RStudio
  when: "'rstudio' not in ansible_facts.packages"
  ansible.builtin.get_url:
    url: "https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.4.1717-amd64.deb"
    dest: "/tmp/rstudio-1.4.1717-amd64.deb"
    checksum: sha256:e27b2645f800c8760fb67d69e89b3a371c4e9e4d517fa81d650f44f3975a1745

- name: Install RStudio
  when: "'rstudio' not in ansible_facts.packages"
  become: yes
  ansible.builtin.apt:
    deb: "/tmp/rstudio-1.4.1717-amd64.deb"

