---
- name: Install package
  become: yes
  apt:
    name:
      - mpd
      - mpv
      - ffmpeg
      - ncmpcpp
      - mpdscribble
      - abcde

- name: Stow MPD Config
  stow:
    name: mpd
    source: "{{ dotfile_path }}"
    overwrite_conflicts: yes

- name: Detect Music Dir state
  stat:
    path: "{{ ansible_env .HOME }}/Music"
  register: music_dir

- name: Delete Music Dir
  file:
    path: "{{ ansible_env .HOME }}/Music"
    state: absent
  when: music_dir.stat.exists and music_dir.stat.isdir

- name: Stow Music Dir
  stow:
    name: music
    source: "{{ dotfile_path }}"
    overwrite_conflicts: yes

- name: Stow Abcde CD Ripper config
  stow:
    name: abcde
    source: "{{ dotfile_path }}"
    overwrite_conflicts: yes

- name: Stop and disable the MPD system service
  become: yes
  systemd:
    name: mpd
    state: stopped
    enabled: no

- name: Start and Enable the MPD user service
  systemd:
    name: mpd
    state: started
    enabled: yes
    user: yes
