---
- name: Configure Kyouko (Thinkpad X250 - My Workstation)
  hosts: all
  roles:
    - name: workstation_common
  tasks:
    - name: Install general tooling
      become: yes
      dnf:
        name:
          - google-noto-sans-fonts
          - tig
          - htop
          - jq

    - name: Create service to manage turbo boost
      become: yes
      template:
        src: disable-turbo-boost.service
        dest: /etc/systemd/system/disable-turbo-boost.service
      register: turbo_boost_service

    - name: reload systemd units
      become: yes
      systemd:
        daemon_reload: yes
      when: turbo_boost_service.changed

    - name: Ensure turbo boost is disabled
      become: yes
      systemd:
        name: disable-turbo-boost
        state: started
        enabled: yes

