---
- name: Configure Kyouko (Thinkpad X250 - My Workstation)
  hosts: all
  roles:
    - name: developer
    - name: workstation_common
    - name: media_playback
    - name: i3
  tasks:
    - name: Install general tooling
      become: yes
      apt:
        name:
          - fonts-font-awesome
          - fonts-noto
          - fonts-open-sans
          - fonts-roboto
          - exfat-fuse
          - tig
          - htop
          - gparted
          - jq

    - name: Ensure bitmap fonts aren't disabled
      become: yes
      command: mv /etc/fonts/conf.d/70-no-bitmaps.conf /etc/fonts/70-no-bitmaps.conf.old
      args:
        removes: /etc/fonts/conf.d/70-no-bitmaps.conf
      register: disable_bitmaps

    - name: Ensure bitmap fonts are enabled
      become: yes
      file:
        src: /etc/fonts/conf.avail/70-yes-bitmaps.conf
        dest: /etc/fonts/conf.d/70-yes-bitmaps.conf
        state: link
      register: enable_bitmaps

    - name: reconfigure fontconfig
      become: yes
      command: dpkg-reconfigure fontconfig
      when: disable_bitmaps.changed or enable_bitmaps.changed

    - name: Create service to manage turbo boost
      become: yes
      template:
        src: disable-turbo-boost.service
        dest: /etc/systemd/system/disable-turbo-boost.service
      register: turbo_boost_service

    - name: reload systemd units
      become: yes
      systemd:
        daemon_reload: yes
      when: turbo_boost_service.changed

    - name: Ensure turbo boost is disabled
      become: yes
      systemd:
        name: disable-turbo-boost
        state: started
        enabled: yes

    - name: Load Thinkpad ACPI for backlight control
      become: yes
      template:
        src: thinkpad-x250.conf
        dest: /etc/modprobe.d/thinkpad-x250.conf

    - name: Install backlight control utility
      become: yes
      apt:
        deb: files/light_1.2_amd64.deb

    - name: Allow backlight control without password
      become: yes
      template:
        src: mattvh-light.conf
        dest: /etc/sudoers.d/10-mattvh-light
        mode: 0440

