---
- name: local Fedora configuration
  hosts: all
  vars:
    - fedora_version: 30
  roles:
    - name: developer
    - name: workstation_common
    - name: jaredhocutt.gnome_extensions
      gnome_extension_ids:
        - 19   # User Themes
        - 2    # Frippery Move Clock
        - 750  # OpenWeather
        - 1297 # Remove Dash
        - 800  # Remove Dropdown Arrows
        - 1708 # Transparent Top Bar
  tasks:
    - name: install the rpmfusion repo packages
      become: yes
      dnf:
        state: present
        name:
          - "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
          - "http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"
    - name: Install general tooling
      become: yes
      dnf:
        state: present
        name:
          - foomatic-db
          - foomatic-db-ppds
          - tig
          - htop
          - gparted
          - jq
    - name: Install multimedia codecs and tools
      become: yes
      dnf:
        name:
          - gstreamer1-plugins-base
          - gstreamer1-plugins-good
          - gstreamer1-plugins-ugly
          - gstreamer1-plugins-bad-free
          - gstreamer1-plugins-bad-freeworld
          - gstreamer1-plugins-bad-free-extras
          - ffmpeg
          - python3-eyed3

