---
- name: local Ubuntu configuration
  hosts: all
  roles:
    - name: developer
    - name: workstation_common
  tasks:
    - name: Install general tooling
      become: yes
      apt:
        state: present
        name:
          - foomatic-db
          - foomatic-db-compressed-ppds
          - exfat-fuse
          - tig
          - htop
          - gparted
          - jq

    - name: Ensure bitmap fonts aren't disabled
      become: yes
      command: mv /etc/fonts/conf.d/70-no-bitmaps.conf /etc/fonts/70-no-bitmaps.conf.old
      args:
        removes: /etc/fonts/conf.d/70-no-bitmaps.conf

    - name: Ensure bitmap fonts are enabled
      become: yes
      file:
        src: /etc/fonts/conf.avail/70-yes-bitmaps.conf
        dest: /etc/fonts/conf.d/70-yes-bitmaps.conf
        state: link

    - name: reconfigure fontconfig
      become: yes
      command: dpkg-reconfigure fontconfig

    - name: Create service to manage turbo boost
      become: yes
      template:
        src: disable-turbo-boost.service
        dest: /etc/systemd/system/disable-turbo-boost.service

    - name: Ensure turbo boost is disabled
      become: yes
      systemd:
        name: disable-turbo-boost
        state: started
        enabled: yes
