---
- name: Regolith PPA
  become: yes
  apt_repository:
    repo: ppa:kgilmer/regolith-stable

- name: Clone Dotfiles
  git:
    repo: "https://github.com/majutsushi/urxvt-font-size.git"
    dest: "{{ ansible_env .HOME }}/.config/urxvt/perls"
    update: no

- name: Install base packages
  become: yes
  apt:
    name:
      - i3-gaps
      - rofi
      - dmenu
      - compton
      - mpd
      - mpc
      - feh
      - rxvt-unicode
    state: latest

- name: Install PyWal
  pip:
    name: pywal

- name: Stow x11 config
  stow:
    name: x11
    source: "{{ ansible_env .HOME }}/.dotfiles"
    overwrite_conflicts: yes

- name: Stow i3 config
  stow:
    name: i3
    source: "{{ ansible_env .HOME }}/.dotfiles"
    overwrite_conflicts: yes

- name: Stow Compton config
  stow:
    name: compton
    source: "{{ ansible_env .HOME }}/.dotfiles"
    overwrite_conflicts: yes
