---
- name: Add fish shell PPA
  become: yes
  ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-3

- name: Add Enpass apt key
  become: yes
  ansible.builtin.apt_key:
    url: "https://apt.enpass.io/keys/enpass-linux.key"
    state: present

- name: Add Enpass deb archive
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb https://apt.enpass.io/ stable main"
    update_cache: yes

- name: Create artifact directory
  file:
    path: "{{ ansible_env .HOME }}/.ansible-artifact"
    state: directory

- name: Clone Dotfiles
  git:
    repo: "git@github.com:eightbitraptor/dotfiles.git"
    dest: "{{ dotfile_path }}"
    update: no

- name: Install Packages
  become: yes
  apt:
    name:
      - tig
      - enpass
      - ripgrep
      - htop
      - curl
      - fish
      - fzf
      - bat
      - glances
      - direnv
      - neovim
      - emacs
      - tmux
    state: present

- name: Stow fish shell config
  stow:
    name: fish
    source: "{{ dotfile_path }}"
    overwrite_conflicts: yes

- name: Set the current users shell to fish
  user:
    name: "{{ ansible_user_id }}"
    shell: "/usr/bin/fish"
  become: yes

- name: Make Vim the default editor
  become: yes
  alternatives:
    name: editor
    path: /usr/bin/vim

- name: Stow Vim config
  stow:
    name: vim
    source: "{{ dotfile_path }}"
    overwrite_conflicts: yes

- name: Install Vim Plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env .HOME }}/.vim/autoload/plug.vim"
  register: plug_installed

- name: Install Vim Plugins with Plug
  command: "vim -E -s -c \"source ~/.vim/vimrc\" +PlugInstall -c \":qa!\""
  when: plug_installed.changed

- name: Stow Emacs config
  stow:
    name: emacs
    source: "{{ dotfile_path }}"
    overwrite_conflicts: yes

- name: Ensure emacs customisations file exists
  file:
    path: "{{ ansible_env .HOME}}/.emacs.d/customisations.el"
    state: file

- name: Install duf
  become: yes
  community.general.snap:
    name: duf-utility
    state: present
