---
- name: Install PPA for Moka Icon set
  become: yes
  apt_repository:
    repo: ppa:snwh/ppa

- name: Create artifact directory
  file:
    path: "{{ ansible_env .HOME }}/.ansible-artifact"
    state: directory

- name: Clone Dotfiles
  git:
    repo: "git@github.com:eightbitraptor/dotfiles.git"
    dest: "{{ dotfile_path }}"
    update: no

- name: Install Packages
  become: yes
  apt:
    name:
      - moka-icon-theme
      - faba-icon-theme
      - faba-mono-icons
      - fonts-firacode
      - rxvt-unicode
      - ranger
      - direnv
      - vim
      - emacs
      - tmux
    state: present

- name: Install fzf
  become: yes
  apt:
    deb: "{{ role_path }}/files/fzf_0.17.5-2_amd64.deb"

- name: Make Vim the default editor
  become: yes
  alternatives:
    name: editor
    path: /usr/bin/vim

- name: Stow Vim config
  stow:
    name: vim
    source: "{{ dotfile_path }}"
    overwrite_conflicts: yes

- name: Install Vim Plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env .HOME }}/.vim/autoload/plug.vim"
  register: plug_installed

- name: Install Vim Plugins with Plug
  command: "vim -E -s -c \"source ~/.vimrc\" +PlugInstall -c \":qa!\""
  when: plug_installed.changed

- name: Stow scripts
  stow:
    name: bin
    source: "{{ dotfile_path }}"
    overwrite_conflicts: yes

- name: Stow Git config
  stow:
    name: git
    source: "{{ dotfile_path }}"
    overwrite_conflicts: yes

- name: Stow Bash config
  stow:
    name: bash
    source: "{{ dotfile_path }}"
    overwrite_conflicts: yes

- name: Stow Emacs config
  stow:
    name: emacs
    source: "{{ dotfile_path }}"
    overwrite_conflicts: yes

- name: Ensure emacs customisations file exists
  file:
    path: "{{ ansible_env .HOME}}/.emacs.d/customisations.el"
    state: touch

- name: Stow Tmux config
  stow:
    name: tmux
    source: "{{ dotfile_path }}"
    overwrite_conflicts: yes

- name: Stow Fonts
  stow:
    name: fonts
    source: "{{ dotfile_path }}"
    overwrite_conflicts: yes
  register: stowed_fonts

- name: Rebuild fc-cache
  command: fc-cache -fv
  when: stowed_fonts.changed
