---
- name: Install multimedia codecs and tools
  become: yes
  dnf:
    state: present
    name:
      - gstreamer1-plugins-base
      - gstreamer1-plugins-good
      - gstreamer1-plugins-ugly
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-bad-free-extras
      - youtube-dl
      - ffmpeg
      - python3-eyed3
      - mpv
